export enum EGender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
}

export enum EAddressOwnershipType {
  OWNER = 'OWNER',
  MORTGAGE = 'MORTGAGE',
  RENTING = 'RENTING',
  BOARDING = 'BOARDING',
  LIVING_WITH_RELATIVES = 'LIVING_WITH_RELATIVES',
  OTHER = 'OTHER',
}

export enum EResidencyStatus {
  AUSTRALIAN_CITIZEN = 'AUSTRALIAN_CITIZEN',
  PERMANENT_RESIDENT = 'PERMANENT_RESIDENT',
  VISA_HOLDER = 'VISA_HOLDER',
}